version: "3"

services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.3
    env_file:
      - ./configs/dev/environment
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    depends_on:
      - aiohttp
    volumes:
      - ./front/app:/static

  aiohttp:
    build: ./sps
    env_file:
      - ./configs/dev/environment
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./sps:/project
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"
