version: "3"

services:
  db:
    image: postgres:9.3
    env_file:
      - environment
    volumes:
      - ./dbdata:/var/lib/postgresql/data


  aiohttp:
    build: .
    env_file:
      - environment
    depends_on:
      - db
    links:
      - db:docker_db
