version: "3"

services:
  redis:
    restart: always
    image: redis:latest

  nginx:
    restart: always
    build: ./configs/prod/nginx/
    ports:
      - "80:80"
    depends_on:
      - aiohttp

  postgres:
    restart: always
    image: postgres:9.3
    env_file:
      - environment

  aiohttp:
    restart: always
    build: ./configs/prod/aiohttp/
    env_file:
      - environment
    environment:
      - PYTHONUNBUFFERED=0
    depends_on:
      - postgres
      - redis
